
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('recipes').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('recipes').insert({id: 1, name: 'Lebanese Cauliflower Soup', instructions: 'Thoroughly wash your cauliflower and cut them into medium-large florets. The smaller you cut them the more they break up in the stew and you definitely want some cauliflower bites .In a large stockpot, bring the beef stew chunks and water to a boil and then let simmer, skimming the fat and impurities continuously until the broth is clean. Once the broth is clean, reduce the heat, cover and let simmer until the meat is tender (about 2 hours). In a food processor, pulse the cilantro and peeled garlic until you have a rough paste. 1/2 of this will go directly into the clean broth. The other half you will save for step 6. In the meantime, prepare a pot for frying and a tray for draining the oil (paper towel works just fine). Once the oil is hot, begin frying the cauliflower in batches until they are a beautiful golden brown. Salt them as they come out and let them drain from any excess oil. Prepare a pan with a bit of vegetable oil and sauté the other half of the cilantro-garlic paste until fragrant. Do not let them burn. Fish out the beef stew chunks from the broth and toss in the pan with the sautéed cilantro-garlic paste. Once browned, return to the stock pot. Transfer your cauliflower into the broth and let simmer for another 30-45 minutes until the cauliflower are tender. Season the stew with salt, pepper, and lemon juice to your liking. The broth should have a mellow sweetness from the cauliflower and a vibrant kick from the lemon, garlic, and cilantro combination. Serve with a side of basmati rice and fresh crunchy radishes.', user_id: 2}),
        knex('recipes').insert({id: 2, name: 'Bacon, Egg and Sausage Breakfast Cups', instructions: 'Preheat oven to 200°C (fan forced). Grease a 12 cup muffin tray. Place 1/2 hash brown in each cup. Push each hash brown so that it covers the base.  Bake for 20-25 minutes or until golden brown. Remove from oven and place 1 tablespoon of baked beans on top of each hash brown. Place a few pieces of bacon and sausage onto each cup. Whisk the eggs and milk together in a jug and pour some into each cup. Spread evenly among the cups. Top each cup with shredded cheese, parsley and pepper. Bake for a further 7-10 minutes until the eggs are cooked and the cheese is melted and browned. Remove and serve.', user_id: 1}),
        knex('recipes').insert({id: 3, name: 'Curried Lentils', instructions: 'Spread the lentils out on a baking sheet to make them easier to see. Pick out any stones or debris. Bring 3 cups of water to a boil in a sauce pot, then add the lentils. Allow the pot to come back up to a boil, then turn the heat to low, place a lid on top, and simmer for 20 minutes, or until the lentils are tender. Drain the cooked lentils in a colander. Meanwhile, mince the garlic and finely dice the onion and carrots. Sauté the onion, garlic, and carrots in a large skillet with olive oil over medium heat until the onions are transparent (about 5 minutes). Add the curry powder and sauté for one minute more. Add the cooked and drained lentils to the skillet, along with the tomato sauce. Stir and heat through (about 5 minutes). Turn the heat off, taste the lentils, and add salt if needed (I added about ½ tsp). Top with fresh cilantro and serve over a bed of rice, with naan, or crusty bread.', user_id: 2}),
        knex('recipes').insert({id: 4, name: 'Sesame Kale', instructions: 'Remove the woody stems from the kale leaves either by slicing down each side with a sharp knife, or by pinching the leaf at the base and pulling out toward the tip. Stack the leaves and then slice crosswise into one inch wide strips. Wash the leaves well in a colander with cool running water. Mince the of garlic and add it to a large pot with one tablespoon of neutral cooking oil (or your favorite cooking oil). Sauté the garlic for about one minute over medium heat. Add the washed kale leaves to the pot. Stir and cook the kale until it is wilted and glossy (about 5 minutes). If you prefer a more tender leaf, cook longer. Add the soy sauce, toasted sesame oil, and sesame seeds to the pot. Stir to coat. Taste and adjust the seasoning to your liking. Serve warm.',  user_id: 3})
      ]);
    });
};
