
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('userrecipes').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('userrecipes').insert({id: 501, name: 'BEEF & MUSHROOM COUNTRY CASSEROL', description: 'Cook the noodles according to the package directions, but until slightly less done. The noodles will further cook while the casserole bakes. Once cooked, drain the pasta and set it aside. While the pasta is cooking, finely dice the onion and slice the mushrooms. Add the cooking oil and ground beef to a large skillet. Cook over medium heat until the beef is fully browned. If using a higher fat content beef, drain off the excess fat before continuing. Add the diced onion, sliced mushrooms, garlic powder, salt, and some freshly cracked pepper to the skillet. Continue to sauté over medium heat until the mushrooms are soft and the onions are transparent. Add the tomato sauce and Worcestershire sauce to the beef and mushroom mixture. Stir to combine, then simmer for a few minutes, or until it thickens slightly. Preheat the oven to 350 degrees. Return the drained noodles to the pot they were boiled in (heat turned off) and add the beef and tomato mixture, diced tomatoes (drained), sour cream, half of the shredded cheddar, and half of the green onions. Stir to combine and then transfer the mixture to a 9x13 inch casserole dish. Top the casserole with the remaining shredded cheese, then bake in the preheated oven for 30 minutes, or until it is bubbling around the edges and the top is starting to brown just slightly. After removing from the oven, sprinkle the remaining green onions over top.', user_id: 501}),
        knex('userrecipes').insert({id: 502, name: 'Buttermilk Biscuits Recipe', description: 'Adjust an oven rack to the middle position and preheat the oven to 425°F. Whisk together the buttermilk and sour cream in a small bowl.In the bowl of a food processor, combine the flour, baking powder, baking soda, and salt and process until blended, about 2 seconds. Scatter the cold butter evenly over the flour and pulse until the mixture resembles coarse meal and the largest butter pieces are about 1/4 inch at their widest. Transfer to a large bowl. Add the buttermilk mixture to the flour mixture and fold with a rubber spatula until just combined. Transfer the dough to a floured work surface and knead until it just comes together, adding extra flour as necessary. With a rolling pin, roll the dough into a 12-inch square. Using a bench scraper, fold the right third of the dough over the center, then fold the left third over so you end up with a 12-by-4-inch rectangle. Fold the top third down over the center, then fold the bottom third up so the whole thing is reduced to a 4-inch square. Press the square down and roll it out again into a 12-inch square. Repeat the folding process once more. (See note above for Cheddar Cheese and Scallion variation.) Roll the dough again into a 12-inch square. Cut six 4-inch rounds out of the dough with a floured biscuit cutter. Transfer the rounds to a parchment-lined baking sheet, spacing them about 1 inch apart. Form the dough scraps into a ball and knead gently 2 or 3 times, until smooth. Roll the dough out until it’s large enough to cut out 2 more 4-inch rounds, and transfer to the baking sheet. Brush the tops of the biscuits with the melted butter and bake until golden brown and well risen, about 15 minutes, rotating the pan halfway through. Allow to cool for 5 minutes and serve.', user_id: 502}),
        knex('userrecipes').insert({id: 503, name: 'Crispy Pan Seared Fish', description: 'Adjust oven rack to center position and preheat oven to 300°F. Pat fish dry on paper towels and season generously with salt and pepper. Place flour, egg, and breadcrumbs in three separate shallow bowls or plates. Season each gently with salt and pepper. Working one piece at at time, lift fish and dip, presentation-side-down, in the flour, followed by the egg, followed by the breadcrumbs, pressing down firmly until a thick layer of breadcrumbs adheres. Place fish breaded-side-up on a clean plate and repeat with remaining fish.Heat oil in a large non-stick or cast iron skillet over medium heat until shimmering. Add fish pieces, breaded-side-down and cook, swirling and rotating them around the pan until deep golden brown, about 5 minutes. Carefully flip fish and transfer to oven. Cook until an instant-read thermometer inserted into the deepest part of the fish registers 140°F, about 5 minutes (a knife or a cake tester inserted into the fish should show no resistance). Serve immediately with lemon wedges or tartar sauce.', user_id: 503}),
        knex('userrecipes').insert({id: 504, name: 'Roasted Butternut Squash Soup', description: 'Heat the oven to 425°F and arrange a rack in the middle. Line a baking sheet with aluminum foil. Place the squash pieces cut-side up on the baking sheet. Melt 1 tablespoon of the butter and brush all of it over the tops and insides of the squash halves (alternatively, you can rub it on evenly with your fingers). Season generously with salt and pepper. Roast until knife tender, 50 minutes to 1 hour. Meanwhile, peel, core, and cut the apple into medium dice. Cut the onion into medium dice. Melt the remaining tablespoon of butter in a large saucepan or Dutch oven over medium heat. Add the apple, onion, and sage, season with salt and pepper, and cook, stirring occasionally, until softened, about 7 minutes. Remove the pan from the heat and set aside. When the squash is ready, set the baking sheet on a wire rack until the squash is cool enough to handle. Using a large spoon, scoop the flesh into the saucepan with the sautéed apples and onions; discard the skins. Add the broth, water, and measured salt and pepper, stir to combine, and bring to a boil over medium-high heat. Reduce the heat to medium low and simmer, stirring occasionally and breaking up any large pieces of squash, until the flavors meld, about 15 minutes. Remove the pan from the heat and stir in the cream. Using a blender, purée the soup in batches until smooth, removing the small cap (the pour lid) from the blender lid and covering the space with a kitchen towel (this allows steam to escape and prevents the blender lid from popping off). Alternatively, use an immersion blender. Taste and season with salt and pepper as needed. Serve garnished with the pumpkin seeds, if using.', user_id: 504})
      ]);
    });
};
